//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agency.Poruke", typeof(Poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno izabrati tip aktivnosti klijenta..
        /// </summary>
        internal static string activity_con {
            get {
                return ResourceManager.GetString("activity_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli novi tip aktivnosti..
        /// </summary>
        internal static string activity_succ {
            get {
                return ResourceManager.GetString("activity_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan izbor grada sa liste.
        /// </summary>
        internal static string city_err {
            get {
                return ResourceManager.GetString("city_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste promjenili podatke klijenta: .
        /// </summary>
        internal static string client_change {
            get {
                return ResourceManager.GetString("client_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli podatke o novom klijentu..
        /// </summary>
        internal static string client_succ {
            get {
                return ResourceManager.GetString("client_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne možete promijeniti status trenutno prijavljenog korisnika!.
        /// </summary>
        internal static string deact_err {
            get {
                return ResourceManager.GetString("deact_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos stručne spreme..
        /// </summary>
        internal static string edu_level_err {
            get {
                return ResourceManager.GetString("edu_level_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli novu školsku spremu..
        /// </summary>
        internal static string education_succ {
            get {
                return ResourceManager.GetString("education_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je zauzeta..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos nije u e-mail formatu..
        /// </summary>
        internal static string email_false {
            get {
                return ResourceManager.GetString("email_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos adrese..
        /// </summary>
        internal static string input_address_err {
            get {
                return ResourceManager.GetString("input_address_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos lozinke..
        /// </summary>
        internal static string input_pass {
            get {
                return ResourceManager.GetString("input_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora biti duža od četiri karaktera..
        /// </summary>
        internal static string input_pass_err {
            get {
                return ResourceManager.GetString("input_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos e-mail adrese..
        /// </summary>
        internal static string input_req_email {
            get {
                return ResourceManager.GetString("input_req_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos imena..
        /// </summary>
        internal static string input_req_name {
            get {
                return ResourceManager.GetString("input_req_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos prezimena..
        /// </summary>
        internal static string input_req_surname {
            get {
                return ResourceManager.GetString("input_req_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos korisničkog imena..
        /// </summary>
        internal static string input_req_user {
            get {
                return ResourceManager.GetString("input_req_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni podaci za prijavu..
        /// </summary>
        internal static string login_err {
            get {
                return ResourceManager.GetString("login_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se prijavili na sistem..
        /// </summary>
        internal static string login_succ {
            get {
                return ResourceManager.GetString("login_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država sa tim nazivom se već nalazi u bazi podataka..
        /// </summary>
        internal static string nazivDrz_con {
            get {
                return ResourceManager.GetString("nazivDrz_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto sa tim nazivom se već nalazi u bazi podataka..
        /// </summary>
        internal static string nazivMjesta_con {
            get {
                return ResourceManager.GetString("nazivMjesta_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string place_err {
            get {
                return ResourceManager.GetString("place_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos cijene..
        /// </summary>
        internal static string price_err {
            get {
                return ResourceManager.GetString("price_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos struke..
        /// </summary>
        internal static string proff_err {
            get {
                return ResourceManager.GetString("proff_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli novu struku..
        /// </summary>
        internal static string proff_succ {
            get {
                return ResourceManager.GetString("proff_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuspješno otkazivanje rezervacije, provjerite pravila sistema..
        /// </summary>
        internal static string reserve_cancel_err {
            get {
                return ResourceManager.GetString("reserve_cancel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radnik je nedostupan u tom periodu. Napravite novu rezervaciju, ili izaberite drugog radnika..
        /// </summary>
        internal static string reserve_err {
            get {
                return ResourceManager.GetString("reserve_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepravilno izabran vremenski period rezervacije. Revidirajte datume..
        /// </summary>
        internal static string reserve_err_reverse {
            get {
                return ResourceManager.GetString("reserve_err_reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok za rezervaciju istekao. Rezervacija mora biti kreirana najmanje jedan dan prije početka aktivnosti..
        /// </summary>
        internal static string reserve_late {
            get {
                return ResourceManager.GetString("reserve_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste kreirali novu rezervaciju..
        /// </summary>
        internal static string reserve_succ {
            get {
                return ResourceManager.GetString("reserve_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli novu ulogu..
        /// </summary>
        internal static string role_succ {
            get {
                return ResourceManager.GetString("role_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je u tabeli izabrati stavku..
        /// </summary>
        internal static string select_miss {
            get {
                return ResourceManager.GetString("select_miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta stučna sprema se već nalazi u bazi podataka..
        /// </summary>
        internal static string strucna_con {
            get {
                return ResourceManager.GetString("strucna_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta struka se već nalazi u bazi podataka..
        /// </summary>
        internal static string struka_con {
            get {
                return ResourceManager.GetString("struka_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taj tip aktivnosti se već nalazi u bazi podataka..
        /// </summary>
        internal static string tipAk_con {
            get {
                return ResourceManager.GetString("tipAk_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos naziva..
        /// </summary>
        internal static string title_con {
            get {
                return ResourceManager.GetString("title_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga je već unesena..
        /// </summary>
        internal static string uloga_con {
            get {
                return ResourceManager.GetString("uloga_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste reaktivirali korisnika .
        /// </summary>
        internal static string user_act {
            get {
                return ResourceManager.GetString("user_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste promijenili pristupne podatke korisniku: .
        /// </summary>
        internal static string user_change_acc {
            get {
                return ResourceManager.GetString("user_change_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste promjenili lične podatke korisniku: .
        /// </summary>
        internal static string user_change_succ {
            get {
                return ResourceManager.GetString("user_change_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste deaktivirali korisnika .
        /// </summary>
        internal static string user_deact {
            get {
                return ResourceManager.GetString("user_deact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli novog korisnika..
        /// </summary>
        internal static string user_succ {
            get {
                return ResourceManager.GetString("user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto..
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s complicated... .
        /// </summary>
        internal static string username_con_case_1 {
            get {
                return ResourceManager.GetString("username_con_case_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Želite li unijeti podatke o još jednom radniku?.
        /// </summary>
        internal static string work_new_input {
            get {
                return ResourceManager.GetString("work_new_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste unijeli podatke o novom radniku..
        /// </summary>
        internal static string work_succ {
            get {
                return ResourceManager.GetString("work_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste promjenili podatke o radniku: .
        /// </summary>
        internal static string worker_change_succ {
            get {
                return ResourceManager.GetString("worker_change_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste deaktivirali status radniku: .
        /// </summary>
        internal static string worker_deact {
            get {
                return ResourceManager.GetString("worker_deact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste reaktivirali status radniku: .
        /// </summary>
        internal static string worker_react {
            get {
                return ResourceManager.GetString("worker_react", resourceCulture);
            }
        }
    }
}
