//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.KorisniciUloge = new HashSet<KorisniciUloge>();
        }
    
        public int KorisnikId { get; set; }
        public int OsobaId { get; set; }
        public string KorisnickoIme { get; set; }
        public Nullable<bool> StatusNaSistemu { get; set; }
        public string LozinkaSalt { get; set; }
        public string LozinkaHash { get; set; }
    
        public virtual Osobe Osobe { get; set; }
        public virtual ICollection<KorisniciUloge> KorisniciUloge { get; set; }
    }
}
