//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcjenaUsluge
    {
        public int OcjenaUslugeId { get; set; }
        public int KlijentId { get; set; }
        public int RezervacijaId { get; set; }
        public int Ocjena { get; set; }
        public string Primjedba { get; set; }
        public string Sugestije { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
