//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osobe
    {
        public Osobe()
        {
            this.Korisnici = new HashSet<Korisnici>();
            this.Radnici = new HashSet<Radnici>();
        }
    
        public int OsobaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string JMBG { get; set; }
        public int AdresaId { get; set; }
        public int MjestoId { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
    
        public virtual Adrese Adrese { get; set; }
        public virtual ICollection<Korisnici> Korisnici { get; set; }
        public virtual Mjesta Mjesta { get; set; }
        public virtual ICollection<Radnici> Radnici { get; set; }
    }
}
