//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racuni
    {
        public int RacunId { get; set; }
        public decimal Iznos { get; set; }
        public Nullable<int> RezervacijaId { get; set; }
        public Nullable<System.DateTime> DatumIspostaveRacuna { get; set; }
    
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
