//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnici
    {
        public Radnici()
        {
            this.StavkeRezervacije = new HashSet<StavkeRezervacije>();
        }
    
        public int RadnikId { get; set; }
        public int OsobaId { get; set; }
        public int StrukaId { get; set; }
        public int SkolskaSpremaId { get; set; }
        public Nullable<decimal> CijenaPoSatu { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DatumPrveRegistracije { get; set; }
    
        public virtual Osobe Osobe { get; set; }
        public virtual SkolskaSprema SkolskaSprema { get; set; }
        public virtual Struka Struka { get; set; }
        public virtual ICollection<StavkeRezervacije> StavkeRezervacije { get; set; }
    }
}
