//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public Rezervacija()
        {
            this.OcjenaUsluge = new HashSet<OcjenaUsluge>();
            this.Racuni = new HashSet<Racuni>();
        }
    
        public int RezervacijaId { get; set; }
        public int KlijentId { get; set; }
        public int StavkeRezervacijeId { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual ICollection<OcjenaUsluge> OcjenaUsluge { get; set; }
        public virtual ICollection<Racuni> Racuni { get; set; }
        public virtual StavkeRezervacije StavkeRezervacije { get; set; }
    }
}
