//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Servis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Struka
    {
        public Struka()
        {
            this.Radnici = new HashSet<Radnici>();
        }
    
        public int StrukaId { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Radnici> Radnici { get; set; }
    }
}
